package acceptance

func init() {
	for step, handler := range map[string]stepHandler{
		"the wall spring barriers task is accepted":                                                                                 acceptStep,
		"spring <spring_id> connects mass <mass_a> to mass <mass_b>":                                                                addBarrierSpring,
		"spring <spring_id> has Wall value <wall>":                                                                                  setBarrierSpringWall,
		"spring <spring_id> has Wall value false":                                                                                   setBarrierSpringWallFalse,
		"spring <spring_id> has Kspring <kspring> Kdamp <kdamp> RestLen <rest_len>":                                                 setBarrierSpringParameters,
		"the coder evaluates spring <spring_id> forces":                                                                             evaluateBarrierSpringForces,
		"spring <spring_id> should apply spring force state <spring_force_state>":                                                   assertBarrierSpringForceState,
		"spring <spring_id> should apply damping force state <damping_force_state>":                                                 assertBarrierSpringDampingState,
		"wall spring <spring_id> endpoints start <initial_length> apart with RestLen <rest_len>":                                    createWallSpringLengthConstraint,
		"the coder advances wall spring length constraint":                                                                          advanceWallSpringLengthConstraint,
		"wall spring <spring_id> endpoint distance should be <expected_length>":                                                     assertWallSpringEndpointDistance,
		"wall spring <spring_id> endpoint correction should be <correction_direction>":                                              assertWallSpringEndpointCorrection,
		"wall spring <spring_id> spans from <wall_x1>, <wall_y1> to <wall_x2>, <wall_y2>":                                           createWallSpringByCoordinates,
		"moving mass <mass_id> starts at <mass_x>, <mass_y> with velocity <mass_vx>, <mass_vy>":                                     createBarrierMovingMass,
		"fast moving mass <mass_id> starts at <mass_x>, <mass_y> with velocity <mass_vx>, <mass_vy>":                                createFastBarrierMovingMass,
		"the coder advances through wall spring collision":                                                                          advanceThroughWallSpringCollision,
		"the coder advances through wall spring collision by <duration>":                                                            advanceThroughWallSpringCollisionByDuration,
		"mass <mass_id> should remain on the starting side of wall spring <spring_id>":                                              assertMassOnStartingWallSpringSide,
		"mass <mass_id> velocity should be resolved away from wall spring <spring_id>":                                              assertMassVelocityResolvedAwayFromWallSpring,
		"moving wall spring <spring_id> spans from <wall_x1>, <wall_y1> to <wall_x2>, <wall_y2> with velocity <wall_vx>, <wall_vy>": createMovingWallSpringByCoordinates,
		"stationary mass <mass_id> starts at <mass_x>, <mass_y>":                                                                    createBarrierStationaryMass,
		"the coder advances through moving wall spring collision":                                                                   advanceThroughWallSpringCollision,
		"mass <mass_id> should remain on the starting side of moving wall spring <spring_id>":                                       assertMassOnStartingWallSpringSide,
		"moving wall spring <spring_id> velocity should be resolved away from mass <mass_id>":                                       assertMovingWallSpringVelocityResolvedAwayFromMass,
		"wall spring <barrier_spring> spans from <barrier_x1>, <barrier_y1> to <barrier_x2>, <barrier_y2>":                          createBarrierWallSpringByCoordinates,
		"constrained wall spring <moving_spring> endpoint <endpoint_a> starts at <endpoint_a_x>, <endpoint_a_y>":                    createConstrainedWallSpringEndpointA,
		"constrained wall spring <moving_spring> endpoint <endpoint_b> starts at <endpoint_b_x>, <endpoint_b_y>":                    createConstrainedWallSpringEndpointB,
		"constrained wall spring <moving_spring> has RestLen <rest_len>":                                                            createConstrainedWallSpring,
		"the coder advances wall spring length constraints and collisions":                                                          advanceWallSpringLengthConstraintsAndCollisions,
		"wall spring endpoint <endpoint_a> should remain on the starting side of wall spring <barrier_spring>":                      assertWallSpringEndpointAOnStartingBarrierSide,
		"wall spring endpoint <endpoint_b> should remain on the starting side of wall spring <barrier_spring>":                      assertWallSpringEndpointBOnStartingBarrierSide,
		"wall spring <spring_id> spans from mass <endpoint_a> to mass <endpoint_b>":                                                 createWallSpringByEndpointIDs,
		"wall spring endpoint <endpoint_a> fixed state is <fixed_a>":                                                                setWallSpringEndpointFixed,
		"wall spring endpoint <endpoint_b> fixed state is <fixed_b>":                                                                setWallSpringEndpointBFixed,
		"moving mass <mass_id> collides with wall spring <spring_id> at contact fraction <contact_fraction>":                        createMassCollidingWithWallSpring,
		"the coder resolves the wall spring collision":                                                                              resolveWallSpringCollision,
		"wall spring endpoint <endpoint_a> should receive impulse share <impulse_share_a>":                                          assertWallSpringEndpointImpulseShare,
		"wall spring endpoint <endpoint_b> should receive impulse share <impulse_share_b>":                                          assertWallSpringEndpointBImpulseShare,
		"wall spring <spring_id> has Temperature <temperature>":                                                                     createWallSpringWithTemperature,
		"temperature random seed is <seed>":                                                                                         setTemperatureRandomSeed,
		"mass <mass_id> should receive temperature kick <kick_behavior>":                                                            assertMassTemperatureKick,
		"spring <spring_id> has Temperature <temperature>":                                                                          setSpringTemperature,
		"moving mass <mass_id> collides with spring <spring_id>":                                                                    createMassCollidingWithSpring,
		"the coder resolves spring collision":                                                                                       resolveSpringCollision,
	} {
		stepHandlers[step] = handler
	}
}
